In [34]:
import pandas as pd
import numpy as np
import cv2

In [57]:
import keras
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.preprocessing.text import Tokenizer
import matplotlib.pyplot as plt
%matplotlib inline
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dropout, Flatten, Dense
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator ,load_img
from keras.layers.normalization import BatchNormalization

In [23]:
df=pd.read_csv("train.csv")

In [24]:
df.shape

(60000, 2)

In [25]:
df.head()

id  label
0   1      9
1   2      0
2   3      0
3   4      3
4   5      0

In [29]:
df["id"]=df["id"].astype(str)

In [30]:
df["id"]=df["id"].apply(lambda x: "train/" + x +".png" )

In [31]:
df.head()

id  label
0  train/1.png      9
1  train/2.png      0
2  train/3.png      0
3  train/4.png      3
4  train/5.png      0

In [35]:
import glob
size=48,48
data=[]
#from PIL import Image
import numpy
for i in df["id"]:
    im = cv2.imread(i)
    im= cv2.resize(im, size)
    np_i = numpy.array(im)
    np_i=np_i/255
    data.append(np_i)

In [37]:
images=np.array(data)

In [39]:
test=pd.read_csv("test.csv")

In [40]:
test["id"]=test["id"].astype(str)

In [41]:
test["id"]=test["id"].apply(lambda x : "test/" + x + ".png")

In [42]:
test.head()

id
0  test/60001.png
1  test/60002.png
2  test/60003.png
3  test/60004.png
4  test/60005.png

In [45]:
import glob
size=48,48
data=[]
#from PIL import Image
import numpy
for i in test["id"]:
    im = cv2.imread(i)
    im= cv2.resize(im, size)
    np_i = numpy.array(im)
    np_i=np_i/255
    data.append(np_i)

In [46]:
test_images=np.array(data)

In [49]:
labels=df["label"]

In [50]:
df["label"].nunique()

10

In [51]:
from keras.utils import to_categorical 
labels = to_categorical(labels,10)

Using TensorFlow backend.


In [55]:
def create_convolutional_model(classes):
    model = Sequential()
    model.add(Conv2D(32,kernel_size=(2,2),strides=(1,1),activation='relu',input_shape=(48,48,3)))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
    model.add(Dropout(0.25))
    
    model.add(Conv2D(filters=64,kernel_size=(2,2),strides=(1,1),activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2),strides=(1,1)))
    model.add(Dropout(0.25))#to prevent neural network from overfitting
    
    model.add(Conv2D(filters=128,kernel_size=(2,2),strides=(1,1),activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2),strides=(1,1)))
    model.add(Dropout(0.25))
    
    model.add(Conv2D(filters=256,kernel_size=(2,2),strides=(1,1),activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2),strides=(1,1)))
    model.add(Dropout(0.25))
    
    model.add(Flatten())
    
    model.add(Dense(256,activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    
    model.add(Dense(512,activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    
    model.add(Dense(classes,activation='softmax'))
    
    
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    
    return model 

In [58]:
classes=10
model = create_convolutional_model(classes)
model.summary()

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 47, 47, 32)        416       
_________________________________________________________________
batch_normalization_1 (Batch (None, 47, 47, 32)        128       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 23, 23, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 23, 23, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 22, 22, 64)        8256      
_________________________________________________________________
batch_normalization_2 (Batch (None, 22, 22, 64)        256       
___________________________

In [59]:
model.compile(loss = "categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])
model.fit(images,labels,batch_size=105,epochs=15,verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/15
 - 448s - loss: 0.4834 - acc: 0.8272
Epoch 2/15
 - 427s - loss: 0.3145 - acc: 0.8843
Epoch 3/15
 - 428s - loss: 0.2718 - acc: 0.8993
Epoch 4/15
 - 428s - loss: 0.2436 - acc: 0.9100
Epoch 5/15
 - 429s - loss: 0.2359 - acc: 0.9127
Epoch 6/15
 - 430s - loss: 0.2081 - acc: 0.9233
Epoch 7/15
 - 430s - loss: 0.1925 - acc: 0.9281
Epoch 8/15
 - 430s - loss: 0.1829 - acc: 0.9308
Epoch 9/15
 - 430s - loss: 0.1678 - acc: 0.9365
Epoch 10/15
 - 438s - loss: 0.1560 - acc: 0.9419
Epoch 11/15
 - 427s - loss: 0.1433 - acc: 0.9453
Epoch 12/15
 - 428s - loss: 0.1336 - acc: 0.9498
Epoch 13/15
 - 427s - loss: 0.1218 - acc: 0.9536
Epoch 14/15
 - 427s - loss: 0.1121 - acc: 0.9579
Epoch 15/15
 - 427s - loss: 0.1022 - acc: 0.9611


In [61]:
y=model.predict(test_images)

In [65]:
labels

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [64]:
y

array([[2.8644665e-13, 3.9255066e-09, 1.9041550e-12, ..., 3.4422388e-07,
        9.6952286e-13, 9.9999964e-01],
       [1.5646922e-03, 2.0637377e-07, 9.9721885e-01, ..., 2.5198121e-06,
        7.4725453e-06, 2.3999703e-06],
       [4.0652526e-14, 1.0000000e+00, 3.7479533e-13, ..., 1.7132500e-13,
        3.0453751e-12, 7.7530349e-15],
       ...,
       [9.2617981e-16, 2.0062858e-15, 3.9581706e-15, ..., 3.1305587e-17,
        1.0000000e+00, 5.1421809e-16],
       [2.1397575e-15, 1.0000000e+00, 1.6088662e-13, ..., 2.9515524e-14,
        3.7529753e-13, 6.5121930e-15],
       [7.6355597e-08, 4.7501683e-08, 2.5001807e-08, ..., 1.2247745e-05,
        3.6987100e-07, 1.0003365e-07]], dtype=float32)

In [66]:
predicted = np.argmax(y, axis=1)

In [67]:
predicted

array([9, 2, 1, ..., 8, 1, 5], dtype=int64)

In [68]:
submission=pd.read_csv("test.csv")

In [69]:
submission["label"]=predicted

In [70]:
submission.head()

id  label
0  60001      9
1  60002      2
2  60003      1
3  60004      1
4  60005      6

In [71]:
submission.to_csv('submission.csv',index=False)